---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-development-build
steps:
- name: push-development-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - feature/*
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: e6wjdT7i0lJmcFsUkspKn2v8ACVwBEH+7IdAsE7UjQXx0NitltdwANtk6O8=
---
kind: secret
name: docker_password
data: 71kw2K1O/TRAuKV/O+LUif/rL+RCegeuyvqcemdtXYK5PeeaREs4hB2wbl/kMevGzvHxxNRph/ttc3redtSmbw==
---
kind: signature
hmac: 961c5478449aa32f5606a51da3b41c001accc4142055c8d7eaccc8a1e0a38b88

...
