pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_BRANCH}"
    secrets: [docker_username, docker_password]
    when:
      event: push
      branch: [development]
